#spring:
#  profiles:
#    active: test

data:
  providers:
    provider1:
      name: provider1
      url: https://provider1-test.com/v1/api/account/validate
    provider2:
      name: provider2
      url: https://provider2-test.com/v2/api/account/validate